// 
// Code generated by a template.
//
using System;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;

namespace Proxy 
{
	[EntityLogicalName("sf_airlines_account")]
	public partial class SfAirlinesAccount : CCLLC.CDS.Sdk.EarlyBound.EntityProxy
	{
		public const string EntityLogicalName = "sf_airlines_account";

		public SfAirlinesAccount()
			: base("sf_airlines_account") {}


		#region Late Bound Field Constants
	
		public class Fields
		{			
			public const string Id = "sf_airlines_accountid";
			public const string Accountid = "accountid";
			public const string SfAirlinesAccountId = "sf_airlines_accountid";
			public const string SfAirlinesid = "sf_airlinesid";
			public const string VersionNumber = "versionnumber";
		}

		#endregion Late Bound Field Constants

		[AttributeLogicalName("sf_airlines_accountid")]
		public override Guid Id
		{
			get => base.Id; 
		}

		[AttributeLogicalName("accountid")]
		public virtual Guid Accountid
		{
			get => GetPropertyValue<Guid>("accountid"); 
		}

		[AttributeLogicalName("sf_airlines_accountid")]
		public virtual Guid SfAirlinesAccountId
		{
			get => GetPropertyValue<Guid>("sf_airlines_accountid"); 
		}

		[AttributeLogicalName("sf_airlinesid")]
		public virtual Guid SfAirlinesid
		{
			get => GetPropertyValue<Guid>("sf_airlinesid"); 
		}

		[AttributeLogicalName("versionnumber")]
		public virtual int? VersionNumber
		{
			get => GetPropertyValue<int?>("versionnumber"); 
		}

	}
}
